import 'package:flutter/material.dart';
import '../models/job.dart';
import '../services/gemini_service.dart';

class InterviewPrepScreen extends StatefulWidget {
  final Job job;
  const InterviewPrepScreen({super.key, required this.job});

  @override
  State<InterviewPrepScreen> createState() => _InterviewPrepScreenState();
}

class _InterviewPrepScreenState extends State<InterviewPrepScreen> {
  bool _loading = true;
  Map<String, dynamic>? _prepData;
  String _error = '';

  @override
  void initState() {
    super.initState();
    _generate();
  }

  Future<void> _generate() async {
    setState(() { _loading = true; _error = ''; });
    try {
      final data = await GeminiService().generateInterviewPrep(
        company: widget.job.company,
        role: widget.job.role,
        description: widget.job.description,
      );
      if (mounted) setState(() { _prepData = data; _loading = false; });
    } catch (e) {
      if (mounted) setState(() { _error = 'Failed to generate. Try again.'; _loading = false; });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Interview Prep', style: TextStyle(fontSize: 18)),
            Text('${widget.job.company} — ${widget.job.role}',
              style: TextStyle(fontSize: 12, color: Colors.grey[600])),
          ],
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          if (!_loading)
            Container(
              margin: const EdgeInsets.only(right: 8),
              decoration: BoxDecoration(
                color: const Color(0xFF0A66C2).withValues(alpha: 0.2),
                borderRadius: BorderRadius.circular(10),
              ),
              child: IconButton(
                icon: const Icon(Icons.refresh_rounded, color: Color(0xFF70B5F9)),
                onPressed: () => _generate(),
              ),
            ),
        ],
      ),
      body: _loading ? _buildLoading() : _error.isNotEmpty ? _buildError() : _buildContent(),
    );
  }

  Widget _buildLoading() {
    return const Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          CircularProgressIndicator(color: Color(0xFF0A66C2)),
          SizedBox(height: 20),
          Text('AI is preparing interview questions...', style: TextStyle(color: const Color(0xFF191919), fontSize: 16)),
          SizedBox(height: 8),
          Text('This may take a moment', style: TextStyle(color: Colors.grey)),
        ],
      ),
    );
  }

  Widget _buildError() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          const Icon(Icons.error_outline_rounded, size: 48, color: Color(0xFFCC1016)),
          const SizedBox(height: 16),
          Text(_error, style: TextStyle(color: Colors.grey[600])),
          const SizedBox(height: 16),
          ElevatedButton.icon(onPressed: _generate, icon: const Icon(Icons.refresh), label: const Text('Retry')),
        ],
      ),
    );
  }

  Widget _buildContent() {
    final tech = _prepData?['technical'] as List? ?? [];
    final behavioral = _prepData?['behavioral'] as List? ?? [];
    final company = _prepData?['company_specific'] as List? ?? [];
    final tips = List<String>.from(_prepData?['tips'] ?? []);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // AI badge
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: BoxDecoration(
              gradient: LinearGradient(colors: [
                const Color(0xFF0A66C2).withValues(alpha: 0.2),
                const Color(0xFFE84393).withValues(alpha: 0.1),
              ]),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: const Color(0xFF0A66C2).withValues(alpha: 0.3)),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(Icons.auto_awesome, size: 16, color: Color(0xFF70B5F9)),
                const SizedBox(width: 8),
                Text('Generated by Gemini AI', style: TextStyle(fontSize: 12, color: Colors.grey[600], fontWeight: FontWeight.w500)),
              ],
            ),
          ),
          const SizedBox(height: 20),

          if (tech.isNotEmpty) _buildSection('Technical Questions', Icons.code_rounded, const Color(0xFF70B5F9), tech),
          if (behavioral.isNotEmpty) _buildSection('Behavioral Questions', Icons.psychology_rounded, const Color(0xFF057642), behavioral),
          if (company.isNotEmpty) _buildSection('Company-Specific', Icons.business_rounded, const Color(0xFFE8A723), company),

          if (tips.isNotEmpty) ...[
            const SizedBox(height: 20),
            const Text('Quick Tips', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: const Color(0xFF191919))),
            const SizedBox(height: 12),
            ...tips.map((tip) => Container(
              margin: const EdgeInsets.only(bottom: 8),
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: const Color(0xFF057642).withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: const Color(0xFF057642).withValues(alpha: 0.3)),
              ),
              child: Row(
                children: [
                  const Icon(Icons.lightbulb_outline, size: 18, color: Color(0xFF057642)),
                  const SizedBox(width: 10),
                  Expanded(child: Text(tip, style: TextStyle(fontSize: 13, color: Colors.grey[700]))),
                ],
              ),
            )),
          ],
          const SizedBox(height: 80),
        ],
      ),
    );
  }

  Widget _buildSection(String title, IconData icon, Color color, List questions) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const SizedBox(height: 8),
        Row(children: [
          Icon(icon, size: 20, color: color),
          const SizedBox(width: 8),
          Text(title, style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: const Color(0xFF191919))),
        ]),
        const SizedBox(height: 12),
        ...questions.map((q) {
          final question = q['question'] ?? '';
          final tip = q['tip'] ?? '';
          return Container(
            margin: const EdgeInsets.only(bottom: 10),
            decoration: BoxDecoration(
              color: const Color(0xFFFFFFFF),
              borderRadius: BorderRadius.circular(14),
              border: Border.all(color: color.withValues(alpha: 0.2)),
            ),
            child: ExpansionTile(
              tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
              childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
              leading: Icon(Icons.help_outline_rounded, size: 20, color: color),
              title: Text(question, style: const TextStyle(fontSize: 14, color: const Color(0xFF191919), fontWeight: FontWeight.w500)),
              iconColor: color,
              collapsedIconColor: Colors.grey,
              children: [
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: color.withValues(alpha: 0.08),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Icon(Icons.tips_and_updates_rounded, size: 16, color: color),
                      const SizedBox(width: 8),
                      Expanded(child: Text(tip, style: TextStyle(fontSize: 13, color: Colors.grey[700], height: 1.5))),
                    ],
                  ),
                ),
              ],
            ),
          );
        }),
        const SizedBox(height: 12),
      ],
    );
  }
}
